### ISSUE TITLE
Occasional "RuntimeError: Session is closed" exceptions

### ISSUE THREAD

**Issue by dvx76** [skodaconnect/myskoda#185]
Getting these every now and then. No persistent or long-term impact it seems.

Authorization:

```
2024-11-09T15:33:26.189450574Z 2024-11-09 15:33:26.042 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved (None)
2024-11-09T15:33:26.189549850Z Traceback (most recent call last):
2024-11-09T15:33:26.189564054Z   File "/usr/local/lib/python3.12/site-packages/myskoda/mqtt.py", line 148, in _connect_and_listen
2024-11-09T15:33:26.189575702Z     password=await self.authorization.get_access_token(),
2024-11-09T15:33:26.189586313Z              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-11-09T15:33:26.189596646Z   File "/usr/local/lib/python3.12/site-packages/myskoda/auth/authorization.py", line 293, in get_access_token
2024-11-09T15:33:26.189607202Z     await self.refresh_token()
2024-11-09T15:33:26.189616942Z   File "/usr/local/lib/python3.12/site-packages/myskoda/auth/authorization.py", line 262, in refresh_token
2024-11-09T15:33:26.189627646Z     if await self._perform_refresh_token():
2024-11-09T15:33:26.189637831Z        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-11-09T15:33:26.189648109Z   File "/usr/local/lib/python3.12/site-packages/myskoda/auth/authorization.py", line 241, in _perform_refresh_token
2024-11-09T15:33:26.189659090Z     async with self.session.post(
2024-11-09T15:33:26.189669201Z   File "/usr/local/lib/python3.12/site-packages/aiohttp/client.py", line 1355, in __aenter__
2024-11-09T15:33:26.189679497Z     self._resp: _RetType = await self._coro
2024-11-09T15:33:26.189689405Z                            ^^^^^^^^^^^^^^^^
2024-11-09T15:33:26.189699090Z   File "/usr/local/lib/python3.12/site-packages/aiohttp/client.py", line 492, in _request
2024-11-09T15:33:26.189709460Z     raise RuntimeError("Session is closed")
2024-11-09T15:33:26.189719682Z RuntimeError: Session is closed
```

get_charging:

```
2024-11-09T14:43:06.962392939Z 2024-11-09 14:43:06.957 ERROR (MainThread) [custom_components.myskoda.coordinator] Unexpected exception from <bound method MySkodaDataUpdateCoordinator._update_charging of <custom_components.myskoda.coordinator.MySkodaDataUpdateCoordinator object at 0x7f4eba39b0>>
2024-11-09T14:43:06.962482901Z Traceback (most recent call last):
2024-11-09T14:43:06.962497123Z   File "/usr/src/homeassistant/homeassistant/helpers/debounce.py", line 137, in _handle_timer_finish
2024-11-09T14:43:06.962508994Z     await task
2024-11-09T14:43:06.962520179Z   File "/config/custom_components/myskoda/coordinator.py", line 196, in _update_charging
2024-11-09T14:43:06.962530845Z     charging = await self.myskoda.get_charging(self.vin)
2024-11-09T14:43:06.962540993Z                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-11-09T14:43:06.962551215Z   File "/usr/local/lib/python3.12/site-packages/myskoda/myskoda.py", line 242, in get_charging
2024-11-09T14:43:06.962561715Z     return (await self.rest_api.get_charging(vin, anonymize=anonymize)).result
2024-11-09T14:43:06.962572030Z             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-11-09T14:43:06.962582641Z   File "/usr/local/lib/python3.12/site-packages/myskoda/rest_api.py", line 119, in get_charging
2024-11-09T14:43:06.962593419Z     data=await self._make_get_request(url),
2024-11-09T14:43:06.962603715Z          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-11-09T14:43:06.962613659Z   File "/usr/local/lib/python3.12/site-packages/myskoda/rest_api.py", line 95, in _make_get_request
2024-11-09T14:43:06.962624048Z     return await self._make_request(url=url, method="GET")
2024-11-09T14:43:06.962634437Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-11-09T14:43:06.962644566Z   File "/usr/local/lib/python3.12/site-packages/myskoda/rest_api.py", line 78, in _make_request
2024-11-09T14:43:06.962655103Z     async with self.session.request(
2024-11-09T14:43:06.962665047Z   File "/usr/local/lib/python3.12/site-packages/aiohttp/client.py", line 1355, in __aenter__
2024-11-09T14:43:06.962675584Z     self._resp: _RetType = await self._coro
2024-11-09T14:43:06.962719084Z                            ^^^^^^^^^^^^^^^^
2024-11-09T14:43:06.962729676Z   File "/usr/local/lib/python3.12/site-packages/aiohttp/client.py", line 492, in _request
2024-11-09T14:43:06.962736750Z     raise RuntimeError("Session is closed")
2024-11-09T14:43:06.962743435Z RuntimeError: Session is closed
```

**Comment by WebSpider** [comment]
Reason for this is probably the new `polling_interval`. As per the documentation in https://github.com/home-assistant/core/blob/85bf8d1374343d96a76603784ef28787e333b7e8/homeassistant/helpers/aiohttp_client.py#L127

>    If auto_cleanup is False, you need to call detach() after the session
    returned is no longer used. Default is True, the session will be
    automatically detached on homeassistant_stop or when being created
    in config entry setup, the config entry is unloaded.

Since `polling_interval` does a reload when the interval is changed, this unloads the config_entry

**Comment by WebSpider** [comment]
I have to figure out what event in HA tracks the unloading of an integration/component, so we can return the session at that point.
