### ISSUE TITLE
mashumaro.exceptions.MissingField: Field "remaining_range_in_km" of type int is missing in EngineRange instance

### ISSUE THREAD

**Issue by jmartens** [skodaconnect/myskoda#193]
I recently noticed the depreciation of the skodaconnect HACS application and instlaled the mysckoda app, but have issues retrieveing the data, from the logs:

```
This error originated from a custom integration.

Logger: custom_components.myskoda.coordinator
Source: helpers/update_coordinator.py:382
integration: MySkoda (documentation, issues)
First occurred: November 9, 2024 at 19:37:05 (263 occurrences)
Last logged: 20:40:02

Unexpected error fetching myskoda data
Traceback (most recent call last):
  File "<string>", line 24, in __mashumaro_from_json__
  File "<string>", line 21, in __mashumaro_from_dict_json__
mashumaro.exceptions.MissingField: Field "remaining_range_in_km" of type int is missing in EngineRange instance

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 382, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/myskoda/coordinator.py", line 94, in _async_update_data
    vehicle = await self.myskoda.get_vehicle(self.vin)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/myskoda/myskoda.py", line 292, in get_vehicle
    vehicle.driving_range = await self.get_driving_range(vin)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/myskoda/myskoda.py", line 258, in get_driving_range
    return (await self.rest_api.get_driving_range(vin, anonymize=anonymize)).result
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/myskoda/rest_api.py", line 177, in get_driving_range
    result = self._deserialize(raw, DrivingRange.from_json)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/myskoda/rest_api.py", line 392, in _deserialize
    data = deserialize(text)
           ^^^^^^^^^^^^^^^^^
  File "<string>", line 26, in __mashumaro_from_json__
mashumaro.exceptions.InvalidFieldValue: Field "primary_engine_range" of type EngineRange in DrivingRange has invalid value {'engineType': 'gasoline', 'currentSoCInPercent': 20, 'currentFuelLevelInPercent': 20}
```

This is for a Skoda Superb iV. If you can guide me I might be able to help in gathering more data to troubleshoot.

**Comment by jmartens** [comment]
Just noticed I reported this issue in myskoda, might be that it needs to be transferred to homeassistant-myskoda.

**Comment by WebSpider** [comment]
The posted information contains all we should need to fix this. Since it is a deserialization error, we can keep it in this repo, since this is where the deserialization happens.

Thanks for your report, we'll fix this in the next release of the integration!
