### ISSUE TITLE
mashumaro.exceptions.MissingField: Field "country" of type str is missing in User instance

### ISSUE THREAD

**Issue by DoriosDE** [skodaconnect/myskoda#210]
I tried to fetch user data via myskoda cli but deserialization fails due to missing country property in payload

(used new myskoda account and updated my profile. I haven't added any cars to my profile)

MySkoda App also does not show a country but I have already added an address and country in account settings

```
myskoda --verbose --user "ANONYMIZED" --password "ANONYMIZED" user

myskoda.myskoda[20] DEBUG IDK Authorization was successful.
myskoda.myskoda[20] DEBUG Myskoda ready.
myskoda.rest_api[20] ERROR Failed to deserialize data: {"id":"ANONYMIZED","email":"ANONYMIZED","firstName":"ANONYMIZED","lastName":"ANONYMIZED","nickname":"ANONYMIZED","preferredLanguage":"ANONYMIZED","dateOfBirth":"ANONYMIZED","capabilities":[{"id":"SPIN_MANAGEMENT"}],"profilePictureUrl":"https://mysmob.api.connect.skoda-auto.cz/api/v1/users/ANONYMIZED/profile-picture?etag=ANONYMIZED"}
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/myskoda/rest_api.py", line 454, in _deserialize
    data = deserialize(text)
           ^^^^^^^^^^^^^^^^^
  File "<string>", line 15, in __mashumaro_from_json__
mashumaro.exceptions.MissingField: Field "country" of type str is missing in User instance
Traceback (most recent call last):
  File "/usr/local/bin/myskoda", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/usr/local/lib/python3.12/site-packages/asyncclick/core.py", line 1205, in __call__
    return anyio.run(self._main, main, args, kwargs, **opts)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/anyio/_core/_eventloop.py", line 74, in run
    return async_backend.run(func, args, {}, backend_options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/anyio/_backends/_asyncio.py", line 2284, in run
    return runner.run(wrapper())
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/anyio/_backends/_asyncio.py", line 2272, in wrapper
    return await func(*args)
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/asyncclick/core.py", line 1208, in _main
    return await main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/asyncclick/core.py", line 1120, in main
    rv = await self.invoke(ctx)
         ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/asyncclick/core.py", line 1739, in invoke
    return await _process_result(await sub_ctx.command.invoke(sub_ctx))
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/asyncclick/core.py", line 1485, in invoke
    return await ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/asyncclick/core.py", line 824, in invoke
    rv = await rv
         ^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/myskoda/cli/requests.py", line 98, in user
    await handle_request(ctx, ctx.obj["myskoda"].get_user, anonymize)
  File "/usr/local/lib/python3.12/site-packages/myskoda/cli/utils.py", line 24, in handle_request
    result = await func(*args)
             ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/myskoda/myskoda.py", line 296, in get_user
    return (await self.rest_api.get_user(anonymize=anonymize)).result
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/myskoda/rest_api.py", line 243, in get_user
    result = self._deserialize(raw, User.from_json)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/myskoda/rest_api.py", line 454, in _deserialize
    data = deserialize(text)
           ^^^^^^^^^^^^^^^^^
  File "<string>", line 15, in __mashumaro_from_json__
mashumaro.exceptions.MissingField: Field "country" of type str is missing in User instance
asyncio[20] ERROR Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f8a562a92b0>
asyncio[20] ERROR Unclosed connector
connections: ['deque([(<aiohttp.client_proto.ResponseHandler object at 0x7f8a55e577d0>, 47063.446875584)])', 'deque([(<aiohttp.client_proto.ResponseHandler object at 0x7f8a55ec9c10>, 47063.820299468)])']
connector: <aiohttp.connector.TCPConnector object at 0x7f8a57ae9b20>
```

**Comment by dvx76** [comment]
Thanks for your report! We can make `country` optional but I suspect with no cars linked to the account you will get a lot more of these type of errors. I'm not sure if it's worth fixing those. Can you please retry once you have a car added to your account?
