### ISSUE TITLE
Error generating fixtures for Octavia iV

### ISSUE THREAD

**Issue by AlexGuld** [skodaconnect/myskoda#269]
When I use the generate fixtures button I get the notification

```
Fixtures Generated
Fixtures for Octavia STYLE 2022 has been successfully generated, check the log.
``` 

When I look in the log I see the following messages. the MySkoda app gets updates from the car fine, and I can activate heating or charging from the app just fine. The integration also gets stats from the car.

```
2024-12-05 11:25:39.822 ERROR (MainThread) [custom_components.myskoda.coordinator] Error received from car in operation ERROR, reason: fail. Requesting MySkoda full update
2024-12-05 11:30:02.131 ERROR (MainThread) [custom_components.myskoda.coordinator] Error received from car in operation ERROR, reason: timeout. Requesting MySkoda full update
2024-12-05 11:30:52.638 ERROR (MainThread) [myskoda.rest_api] Invalid status for GET request to /v1/charging/TMBAW7NX5NYXXXXXX: 500
Traceback (most recent call last):
  File "/usr/local/lib/python3.13/site-packages/myskoda/rest_api.py", line 94, in _make_request
    response.raise_for_status()
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/local/lib/python3.13/site-packages/aiohttp/client_reqrep.py", line 1157, in raise_for_status
    raise ClientResponseError(
    ...<5 lines>...
    )
aiohttp.client_exceptions.ClientResponseError: 500, message='Internal Server Error', url='https://mysmob.api.connect.skoda-auto.cz/api/v1/charging/TMBAW7NX5NYXXXXXX'
2024-12-05 11:30:52.642 ERROR (MainThread) [custom_components.myskoda.error_handlers] Error requesting vehicle update from MySkoda API: Internal Server Error (500), ignoring this

2024-12-05 14:14:57.400 ERROR (MainThread) [myskoda.rest_api] Invalid status for GET request to /v2/air-conditioning/TMBAW7NX5NYXXXXXX/auxiliary-heating: 500
Traceback (most recent call last):
  File "/usr/local/lib/python3.13/site-packages/myskoda/rest_api.py", line 94, in _make_request
    response.raise_for_status()
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/local/lib/python3.13/site-packages/aiohttp/client_reqrep.py", line 1157, in raise_for_status
    raise ClientResponseError(
    ...<5 lines>...
    )
aiohttp.client_exceptions.ClientResponseError: 500, message='Internal Server Error', url='https://mysmob.api.connect.skoda-auto.cz/api/v2/air-conditioning/TMBAW7NX5NYXXXXXX/auxiliary-heating'
```

**Comment by dvx76** [comment]
These could be normal. Generate Fixtures will try _all_ endpoints including the ones which may not be supported for your car model. Look for an INFO message with a whole bunch of json. That's the fixture.

**Comment by AlexGuld** [comment]
There is no other info then what I have posted here. Unless I'm blind. 🙃

**Comment by dvx76** [comment]
Do you see any INFO messages at all? Could be you're only logging (or filtering) WARNING or higher. This is what I get after clicking the button. You're looking for the last message (which goes on for much longer.

```
# Bunch more errors before this
2024-12-05T19:31:51.193894816Z 2024-12-05 19:31:51.187 ERROR (MainThread) [myskoda.rest_api] Invalid status for GET request to /v1/trip-statistics/TMBJCXXXXXXXX?offsetType=week&offset=0&timezone=Europe%2FBerlin: 404
2024-12-05T19:31:51.193985241Z Traceback (most recent call last):
2024-12-05T19:31:51.193994630Z   File "/usr/local/lib/python3.12/site-packages/myskoda/rest_api.py", line 94, in _make_request
2024-12-05T19:31:51.194002389Z     response.raise_for_status()
2024-12-05T19:31:51.194009241Z   File "/usr/local/lib/python3.12/site-packages/aiohttp/client_reqrep.py", line 1158, in raise_for_status
2024-12-05T19:31:51.194016334Z     raise ClientResponseError(
2024-12-05T19:31:51.194023056Z aiohttp.client_exceptions.ClientResponseError: 404, message='Not Found', url='https://mysmob.api.connect.skoda-auto.cz/api/v1/trip-statistics/TMBJCXXXXXXXX?offsetType=week&offset=0&timezone=Europe/Berlin'
2024-12-05T19:31:51.196222854Z 2024-12-05 19:31:51.190 INFO (MainThread) [custom_components.myskoda.button] Fixtures for Enyaq 80 2022: {"name":"Enyaq","description":"Fixtures for Enyaq 80 2022","generation_time":"2024-12-05T19:31:51.189966+00:00","library_version":"0.14.2","vehicles":[{"id":0,"device_platform":"WCAR","system_model_id":"5AZJJ2","model":"Enyaq","model_year":"2022","trim_level":"80","software_version":"3.7","capabilities":[{"id":"AUTOMATION","statuses":[]},{"id":"BATTERY_CHARGING_CARE","statuses":[]},{"id":"BATTERY_SUPPORT","statuses":[]},{"id":"CHARGING_PROFILES","statuses":[]},{"id":"CHARGING_STATIONS","statuses":[]},{"id":"DEALER_APPOINTMENT","statuses":[]},{"id":"DIGICERT","statuses":[]},{"id":"MAP_UPDATE","statuses":[]},{"id":"MEASUREMENTS"
```

**Comment by AlexGuld** [comment]
Yep it's my fault. At some point I changed log level to warning 😖

Now I have changed it to info I see all the messages 🥳
