### ISSUE TITLE
MQTT event field can have lowercase values

### ISSUE THREAD

**Issue by dvx76** [skodaconnect/myskoda#55]
```
2024-09-29 10:20:13 WALLY myskoda.mqtt[25433] DEBUG Message (service-event) received for TMBxxx on topic charging: b'{"version":1,"traceId":"a1877638-cd2d-4907-8716-f9c0292e4794","timestamp":"2024-09-29T08:19:49Z","producer":"SKODA_MHUB","name":"change-soc","data":{"mode":"manual","state":"charging","soc":"67","chargedRange":"324","timeToFinish":"200","userId":"uuid","vin":"TMBxxxx"}}'
2024-09-29 10:20:13 WALLY asyncio[25433] ERROR Exception in callback Client.loop_read()
handle: <Handle Client.loop_read()>
Traceback (most recent call last):
  File "<string>", line 15, in __mashumaro_from_dict__
  File "/home/fdevaux/.pyenv/versions/3.12.2/lib/python3.12/enum.py", line 744, in __call__
    return cls.__new__(cls, value)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fdevaux/.pyenv/versions/3.12.2/lib/python3.12/enum.py", line 1158, in __new__
    raise ve_exc
ValueError: 'manual' is not a valid ChargeMode
```

- Option 1: Allow select Enums to ignore case (e.g. https://stackoverflow.com/a/76131490)
- Option 2: Deserialize all string values to lowercase and have all StrEnum values as lowercase. 

> Joostlek — Today at 10:42
> Lower case is nice because our translation files work with snake_case
> You could also consider making non essential values optional. In Withings I have a few enums that are optional, so i made a thing that puts in the log like, hey, this measurement unit is not part of the enum, please open an issue at this repo

**Comment by WebSpider** [comment]
This is currently sending my 2024.10.b install in a logging loop, logging about 40MB/min.

**Comment by dvx76** [comment]
@WebSpider it's not really this specific issue which makes MQTT go berserk. It's _any_ issue parsing the event. I'm fixing this specific parse issue here but I'll try to take a look at the generic MQTT issue today as part of skodaconnect/homeassistant-skodaconnect#63
