### ISSUE TITLE
Trip statistics endpoint

### ISSUE THREAD

**Issue by OBerghmans** [skodaconnect/myskoda#58]
I get the following error when running the CLI command `trip-statistics`:

```
2024-09-29 13:20:02 myskoda.myskoda[10496] INFO IDK Authorization was successful.
2024-09-29 13:20:02 myskoda.rest_api[10496] ERROR Failed to load data from url /v1/trip-statistics/TMBXYZ123?offsetType=week&offset=0&timezone=Europe%2FBerlin. Return value was 'Vehicle with VIN {TMBXYZ123} not found'
Traceback (most recent call last):
  File "C:\Users\oli\Local\personal\myskoda\myskoda\rest_api.py", line 41, in _make_get_request
    data = deserialize(response_text)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 3, in __mashumaro_from_json__
orjson.JSONDecodeError: unexpected character: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\oli\AppData\Local\pypoetry\Cache\virtualenvs\myskoda-jII21Bdp-py3.12\Lib\site-packages\asyncclick\core.py", line 1205, in __call__
    return anyio.run(self._main, main, args, kwargs, **opts)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oli\AppData\Local\pypoetry\Cache\virtualenvs\myskoda-jII21Bdp-py3.12\Lib\site-packages\anyio\_core\_eventloop.py", line 74, in run
    return async_backend.run(func, args, {}, backend_options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oli\AppData\Local\pypoetry\Cache\virtualenvs\myskoda-jII21Bdp-py3.12\Lib\site-packages\anyio\_backends\_asyncio.py", line 2248, in run
    return runner.run(wrapper())
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oli\.pyenv\pyenv-win\versions\3.12.2\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oli\.pyenv\pyenv-win\versions\3.12.2\Lib\asyncio\base_events.py", line 685, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\oli\AppData\Local\pypoetry\Cache\virtualenvs\myskoda-jII21Bdp-py3.12\Lib\site-packages\anyio\_backends\_asyncio.py", line 2236, in wrapper
    return await func(*args)
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\oli\AppData\Local\pypoetry\Cache\virtualenvs\myskoda-jII21Bdp-py3.12\Lib\site-packages\asyncclick\core.py", line 1208, in _main
    return await main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oli\AppData\Local\pypoetry\Cache\virtualenvs\myskoda-jII21Bdp-py3.12\Lib\site-packages\asyncclick\core.py", line 1120, in main
    rv = await self.invoke(ctx)
         ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oli\AppData\Local\pypoetry\Cache\virtualenvs\myskoda-jII21Bdp-py3.12\Lib\site-packages\asyncclick\core.py", line 1739, in invoke
    return await _process_result(await sub_ctx.command.invoke(sub_ctx))
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oli\AppData\Local\pypoetry\Cache\virtualenvs\myskoda-jII21Bdp-py3.12\Lib\site-packages\asyncclick\core.py", line 1485, in invoke
    return await ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oli\AppData\Local\pypoetry\Cache\virtualenvs\myskoda-jII21Bdp-py3.12\Lib\site-packages\asyncclick\core.py", line 824, in invoke
    rv = await rv
         ^^^^^^^^
  File "C:\Users\oli\Local\personal\myskoda\myskoda\cli.py", line 316, in trip_statistics
    stats = await myskoda.get_trip_statistics(vin)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oli\Local\personal\myskoda\myskoda\myskoda.py", line 200, in get_trip_statistics
    return await self.rest_api.get_trip_statistics(vin)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oli\Local\personal\myskoda\myskoda\rest_api.py", line 83, in get_trip_statistics
    return await self._make_get_request(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oli\Local\personal\myskoda\myskoda\rest_api.py", line 41, in _make_get_request
    data = deserialize(response_text)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 3, in __mashumaro_from_json__
orjson.JSONDecodeError: unexpected character: line 1 column 1 (char 0)
2024-09-29 13:20:02 asyncio[10496] ERROR Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000001A98659FA70>
2024-09-29 13:20:02 asyncio[10496] ERROR Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x000001A98683B890>, 190083.359)]', '[(<aiohttp.client_proto.ResponseHandler object at 0x000001A986894AD0>, 190083.828)]']
connector: <aiohttp.connector.TCPConnector object at 0x000001A9868934A0>
```

Perhaps because my car is rather new and now trips were recorded yet?

**Comment by WebSpider** [comment]
What version of the lib are you running?

Also, not all cars support trip statistics. What car do you have connected?

**Comment by sonar98** [comment]
I've got the same error. I'm running version 0.6.2.

Car is an Enyaq 80 model year 2022. Sw version 3.0.

**Comment by OBerghmans** [comment]
Lib version is 0.6.2 (actually main branch + my mqtt flag changes as mqtt is not working on my windows)

Car is Enyaq 85x model year 2025. Sw version 5.0:

```
battery capacity: 77kwh
power: 210kw
engine: iV
model: Enyaq Coupé
model id: 5ACJK4
model year: 2025
title: Škoda Enyaq Coupé
software: 5.0
```

Might indeed be that my cars does not support trip statistics. We could catch the return value and print it, So that it does not throw an exception.

**Comment by dvx76** [comment]
Definitely no trip statistics on Enyaq.

The CLI is just meant to expose all available methods so it's easy to test things. The integration will use `get_vehicle` which will only try to get statistics if the `TRIP_STATISTICS` capability is present.

**Comment by OBerghmans** [comment]
It's a pity the API doesn't reply with a JSON message, albeit some sort of error json. Now it just returns a string.

**Comment by thetoaster** [comment]
Just a heads up, I've implemented single trip statistics alongside overall statistics in PR #507 which should expose the underlying values for the homeassistant component to consume.
