### ISSUE TITLE
Error when using integration with Suberb iV

### ISSUE THREAD

**Issue by WebSpider** [skodaconnect/myskoda#86]
```text
Logger: myskoda.rest_api
Source: /usr/local/lib/python3.12/site-packages/myskoda/rest_api.py:44
First occurred: 11:19:20 AM (6 occurrences)
Last logged: 11:21:58 AM

Failed to load data from url /v1/charging/TMBXXXXXXXXXX. Return value was '{"isVehicleInSavedLocation":false,"status":{"remainingTimeToFullyChargedInMinutes":140,"state":"CHARGING","chargeType":"AC","battery":{"remainingCruisingRangeInMeters":23000,"stateOfChargeInPercent":60}},"settings":{"availableChargeModes":[]},"carCapturedTimestamp":"2024-10-07T09:10:25Z","errors":[{"type":"CARE_MODE_IS_NOT_AVAILABLE","description":"Care mode is not available."},{"type":"AUTO_UNLOCK_IS_NOT_AVAILABLE","description":"Auto unlock is not available."},{"type":"MAX_CHARGE_CURRENT_IS_NOT_AVAILABLE","description":"Maximal charge current is not available."},{"type":"CHARGE_LIMIT_IS_NOT_AVAILABLE","description":"Charge limit is not available."}]}'
Failed to load data from url /v1/charging/TMBXXXXXXXXXX. Return value was '{"isVehicleInSavedLocation":false,"status":{"state":"READY_FOR_CHARGING","chargeType":"OFF","battery":{"remainingCruisingRangeInMeters":25000,"stateOfChargeInPercent":63}},"settings":{"availableChargeModes":[]},"carCapturedTimestamp":"2024-10-07T09:21:37Z","errors":[{"type":"CARE_MODE_IS_NOT_AVAILABLE","description":"Care mode is not available."},{"type":"AUTO_UNLOCK_IS_NOT_AVAILABLE","description":"Auto unlock is not available."},{"type":"MAX_CHARGE_CURRENT_IS_NOT_AVAILABLE","description":"Maximal charge current is not available."},{"type":"CHARGE_LIMIT_IS_NOT_AVAILABLE","description":"Charge limit is not available."}]}'
Traceback (most recent call last):
  File "<string>", line 16, in __mashumaro_from_json__
  File "<string>", line 14, in __mashumaro_from_dict_json__
mashumaro.exceptions.MissingField: Field "max_charge_current_ac" of type MaxChargeCurrent is missing in Settings instance
```

**Comment by prvakt** [comment]
and same error also in case cable is unplugged
```Failed to load data from url /v1/charging/TMBXXXXXXXXXXXXXX. Return value was '{"isVehicleInSavedLocation":false,"status":{"state":"CONNECT_CABLE","chargeType":"OFF","battery":{"remainingCruisingRangeInMeters":25000,"stateOfChargeInPercent":63}},"settings":{"availableChargeModes":[]},"carCapturedTimestamp":"2024-10-07T09:36:22Z","errors":[{"type":"CARE_MODE_IS_NOT_AVAILABLE","description":"Care mode is not available."},{"type":"AUTO_UNLOCK_IS_NOT_AVAILABLE","description":"Auto unlock is not available."},{"type":"MAX_CHARGE_CURRENT_IS_NOT_AVAILABLE","description":"Maximal charge current is not available."},{"type":"CHARGE_LIMIT_IS_NOT_AVAILABLE","description":"Charge limit is not available."}]}'```
